"""empty message

Revision ID: 39573ecb2a42
Revises: bae5ce4cbfcd
Create Date: 2021-04-04 19:05:47.421140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39573ecb2a42'
down_revision = 'bae5ce4cbfcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
